name: CI
on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up micromamba
        uses: mamba-org/setup-micromamba@v2
        with:
          environment-file: environment.yml
          environment-name: ci
          cache-downloads: true
          cache-env: true
      - name: Install project extras
        shell: bash -l {0}
        run: |
          micromamba run -n ci pip install -e .[dev,service]
      - name: Run tests
        shell: bash -l {0}
        run: |
          micromamba run -n ci python -V
          micromamba run -n ci pytest -q
      - name: Lint
        shell: bash -l {0}
        run: |
          micromamba run -n ci ruff check src tests
